// Mocks generated by Mockito 5.4.6 from annotations
// in pocketcrm/test/core/di/providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pocketcrm/domain/models/company.dart' as _i3;
import 'package:pocketcrm/domain/models/contact.dart' as _i2;
import 'package:pocketcrm/domain/models/note.dart' as _i4;
import 'package:pocketcrm/domain/models/task.dart' as _i5;
import 'package:pocketcrm/domain/repositories/crm_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContact_0 extends _i1.SmartFake implements _i2.Contact {
  _FakeContact_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompany_1 extends _i1.SmartFake implements _i3.Company {
  _FakeCompany_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNote_2 extends _i1.SmartFake implements _i4.Note {
  _FakeNote_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_3 extends _i1.SmartFake implements _i5.Task {
  _FakeTask_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CRMRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCRMRepository extends _i1.Mock implements _i6.CRMRepository {
  @override
  _i7.Future<bool> testConnection(String? baseUrl, String? apiToken) =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, [baseUrl, apiToken]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String> getCurrentUserName() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserName, []),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getCurrentUserName, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getCurrentUserName, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<
    ({List<_i2.Contact> contacts, String? endCursor, bool hasNextPage})
  >
  getContacts({String? search, int? pageSize = 20, String? after}) =>
      (super.noSuchMethod(
            Invocation.method(#getContacts, [], {
              #search: search,
              #pageSize: pageSize,
              #after: after,
            }),
            returnValue:
                _i7.Future<
                  ({
                    List<_i2.Contact> contacts,
                    String? endCursor,
                    bool hasNextPage,
                  })
                >.value((
                  contacts: <_i2.Contact>[],
                  endCursor: null,
                  hasNextPage: false,
                )),
            returnValueForMissingStub:
                _i7.Future<
                  ({
                    List<_i2.Contact> contacts,
                    String? endCursor,
                    bool hasNextPage,
                  })
                >.value((
                  contacts: <_i2.Contact>[],
                  endCursor: null,
                  hasNextPage: false,
                )),
          )
          as _i7.Future<
            ({List<_i2.Contact> contacts, String? endCursor, bool hasNextPage})
          >);

  @override
  _i7.Future<List<_i2.Contact>> getContactsByCompany(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getContactsByCompany, [companyId]),
            returnValue: _i7.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Contact>>.value(
              <_i2.Contact>[],
            ),
          )
          as _i7.Future<List<_i2.Contact>>);

  @override
  _i7.Future<List<_i2.Contact>> getContactsByTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getContactsByTask, [taskId]),
            returnValue: _i7.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Contact>>.value(
              <_i2.Contact>[],
            ),
          )
          as _i7.Future<List<_i2.Contact>>);

  @override
  _i7.Future<_i2.Contact> getContactById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContactById, [id]),
            returnValue: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(this, Invocation.method(#getContactById, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(this, Invocation.method(#getContactById, [id])),
            ),
          )
          as _i7.Future<_i2.Contact>);

  @override
  _i7.Future<_i2.Contact> createContact({
    required String? firstName,
    required String? lastName,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createContact, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(
                this,
                Invocation.method(#createContact, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(
                this,
                Invocation.method(#createContact, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Contact>);

  @override
  _i7.Future<_i2.Contact> updateContact(
    String? id, {
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
    String? companyId,
    bool? clearCompany = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateContact,
              [id],
              {
                #firstName: firstName,
                #lastName: lastName,
                #email: email,
                #phone: phone,
                #companyId: companyId,
                #clearCompany: clearCompany,
              },
            ),
            returnValue: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(
                this,
                Invocation.method(
                  #updateContact,
                  [id],
                  {
                    #firstName: firstName,
                    #lastName: lastName,
                    #email: email,
                    #phone: phone,
                    #companyId: companyId,
                    #clearCompany: clearCompany,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Contact>.value(
              _FakeContact_0(
                this,
                Invocation.method(
                  #updateContact,
                  [id],
                  {
                    #firstName: firstName,
                    #lastName: lastName,
                    #email: email,
                    #phone: phone,
                    #companyId: companyId,
                    #clearCompany: clearCompany,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Contact>);

  @override
  _i7.Future<void> deleteContact(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Company>> getCompanies({String? search, int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanies, [], {
              #search: search,
              #page: page,
            }),
            returnValue: _i7.Future<List<_i3.Company>>.value(<_i3.Company>[]),
            returnValueForMissingStub: _i7.Future<List<_i3.Company>>.value(
              <_i3.Company>[],
            ),
          )
          as _i7.Future<List<_i3.Company>>);

  @override
  _i7.Future<_i3.Company> getCompanyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyById, [id]),
            returnValue: _i7.Future<_i3.Company>.value(
              _FakeCompany_1(this, Invocation.method(#getCompanyById, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Company>.value(
              _FakeCompany_1(this, Invocation.method(#getCompanyById, [id])),
            ),
          )
          as _i7.Future<_i3.Company>);

  @override
  _i7.Future<_i3.Company> createCompany({
    required String? name,
    String? domainName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCompany, [], {
              #name: name,
              #domainName: domainName,
            }),
            returnValue: _i7.Future<_i3.Company>.value(
              _FakeCompany_1(
                this,
                Invocation.method(#createCompany, [], {
                  #name: name,
                  #domainName: domainName,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Company>.value(
              _FakeCompany_1(
                this,
                Invocation.method(#createCompany, [], {
                  #name: name,
                  #domainName: domainName,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Company>);

  @override
  _i7.Future<List<_i4.Note>> getNotesByContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByContact, [contactId]),
            returnValue: _i7.Future<List<_i4.Note>>.value(<_i4.Note>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Note>>.value(
              <_i4.Note>[],
            ),
          )
          as _i7.Future<List<_i4.Note>>);

  @override
  _i7.Future<List<_i4.Note>> getNotesByCompany(String? companyId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByCompany, [companyId]),
            returnValue: _i7.Future<List<_i4.Note>>.value(<_i4.Note>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Note>>.value(
              <_i4.Note>[],
            ),
          )
          as _i7.Future<List<_i4.Note>>);

  @override
  _i7.Future<_i4.Note> createNote({
    required String? contactId,
    required String? body,
    DateTime? dueAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [], {
              #contactId: contactId,
              #body: body,
              #dueAt: dueAt,
            }),
            returnValue: _i7.Future<_i4.Note>.value(
              _FakeNote_2(
                this,
                Invocation.method(#createNote, [], {
                  #contactId: contactId,
                  #body: body,
                  #dueAt: dueAt,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Note>.value(
              _FakeNote_2(
                this,
                Invocation.method(#createNote, [], {
                  #contactId: contactId,
                  #body: body,
                  #dueAt: dueAt,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.Note>);

  @override
  _i7.Future<_i4.Note> updateNote(
    String? id, {
    required String? body,
    DateTime? dueAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [id], {#body: body, #dueAt: dueAt}),
            returnValue: _i7.Future<_i4.Note>.value(
              _FakeNote_2(
                this,
                Invocation.method(
                  #updateNote,
                  [id],
                  {#body: body, #dueAt: dueAt},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Note>.value(
              _FakeNote_2(
                this,
                Invocation.method(
                  #updateNote,
                  [id],
                  {#body: body, #dueAt: dueAt},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Note>);

  @override
  _i7.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.Task>> getTasks({bool? completed}) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {#completed: completed}),
            returnValue: _i7.Future<List<_i5.Task>>.value(<_i5.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Task>>.value(
              <_i5.Task>[],
            ),
          )
          as _i7.Future<List<_i5.Task>>);

  @override
  _i7.Future<List<_i5.Task>> getOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, []),
            returnValue: _i7.Future<List<_i5.Task>>.value(<_i5.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Task>>.value(
              <_i5.Task>[],
            ),
          )
          as _i7.Future<List<_i5.Task>>);

  @override
  _i7.Future<List<_i5.Task>> getTodayTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, []),
            returnValue: _i7.Future<List<_i5.Task>>.value(<_i5.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Task>>.value(
              <_i5.Task>[],
            ),
          )
          as _i7.Future<List<_i5.Task>>);

  @override
  _i7.Future<List<_i5.Task>> getTomorrowTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTomorrowTasks, []),
            returnValue: _i7.Future<List<_i5.Task>>.value(<_i5.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i5.Task>>.value(
              <_i5.Task>[],
            ),
          )
          as _i7.Future<List<_i5.Task>>);

  @override
  _i7.Future<_i5.Task> createTask({
    required String? title,
    String? body,
    DateTime? dueAt,
    String? contactId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #title: title,
              #body: body,
              #dueAt: dueAt,
              #contactId: contactId,
            }),
            returnValue: _i7.Future<_i5.Task>.value(
              _FakeTask_3(
                this,
                Invocation.method(#createTask, [], {
                  #title: title,
                  #body: body,
                  #dueAt: dueAt,
                  #contactId: contactId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Task>.value(
              _FakeTask_3(
                this,
                Invocation.method(#createTask, [], {
                  #title: title,
                  #body: body,
                  #dueAt: dueAt,
                  #contactId: contactId,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Task>);

  @override
  _i7.Future<_i5.Task> updateTask(
    String? id, {
    String? title,
    String? body,
    DateTime? dueAt,
    bool? clearDueDate = false,
    bool? completed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTask,
              [id],
              {
                #title: title,
                #body: body,
                #dueAt: dueAt,
                #clearDueDate: clearDueDate,
                #completed: completed,
              },
            ),
            returnValue: _i7.Future<_i5.Task>.value(
              _FakeTask_3(
                this,
                Invocation.method(
                  #updateTask,
                  [id],
                  {
                    #title: title,
                    #body: body,
                    #dueAt: dueAt,
                    #clearDueDate: clearDueDate,
                    #completed: completed,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Task>.value(
              _FakeTask_3(
                this,
                Invocation.method(
                  #updateTask,
                  [id],
                  {
                    #title: title,
                    #body: body,
                    #dueAt: dueAt,
                    #clearDueDate: clearDueDate,
                    #completed: completed,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Task>);

  @override
  _i7.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.Contact>> getRecentContacts({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentContacts, [], {#limit: limit}),
            returnValue: _i7.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Contact>>.value(
              <_i2.Contact>[],
            ),
          )
          as _i7.Future<List<_i2.Contact>>);
}
